<?php

namespace onmotion\survey\models;


use Yii;
use yii\base\Exception;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "survey_question".
 *
 * @property integer $survey_question_id
 * @property string $survey_question_name
 * @property string $survey_question_descr
 * @property integer $survey_question_type
 * @property integer $survey_question_survey_id
 * @property boolean $survey_question_can_skip
 * @property boolean $survey_question_show_descr
 * @property boolean $survey_question_is_scorable
 *
 * @property SurveyAnswer[] $answers
 * @property Survey $survey
 * @property SurveyType $questionType
 * @property SurveyUserAnswer[] $userAnswers
 */
class SurveyQuestion extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'survey_question';
    }

    public function validateMultipleAnswer()
    {
        $question = $this;
        $userAnswers = $question->userAnswers;
        if (!$question->survey_question_can_skip){
            if ($question->survey_question_type === SurveyType::TYPE_MULTIPLE){
                $answerValues = ArrayHelper::getColumn($userAnswers, 'survey_user_answer_value');
                if (!in_array("1", $answerValues)){
                    $answer = (array)$question->userAnswers;
                    if(!empty($answer)) {
                        end($answer)->addError('survey_user_answer_value', \Yii::t('survey', 'You must enter an answer'));
                    }
                }
            }
        }
        return true;
    }

    public function changeDefaultValuesOnTypeChange(){
        /** @var SurveyQuestion $question */
        $question = $this;
        $oldType = $question->getOldAttribute('survey_question_type');
        $newType = $question->getAttribute('survey_question_type');
        if ($oldType === $newType){
            return true;
        }

        if ($newType === SurveyType::TYPE_SLIDER){
            $question->unlinkAll('answers', true);
            for ($i = 1; $i <= 2; ++$i) {
                $answer = new SurveyAnswer();
                $answer->survey_answer_sort = $i;
                $answer->survey_answer_name = ($i === 1) ? 0 : 100;
                $question->link('answers', $answer);
            }
        }else if($oldType === SurveyType::TYPE_SLIDER){
            $question->unlinkAll('answers', true);
            for ($i = 1; $i <= 2; ++$i) {
                $answer = new SurveyAnswer();
                $answer->survey_answer_sort = $i;
                $question->link('answers', $answer);
            }
        }

        return true;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['survey_question_descr'], 'string'],
            [['survey_question_type', 'survey_question_survey_id'], 'integer'],
            [['survey_question_type'], 'filter', 'filter' => 'intval'],
            [['survey_question_can_skip', 'survey_question_show_descr', 'survey_question_is_scorable'], 'boolean'],
            [['survey_question_can_skip', 'survey_question_show_descr', 'survey_question_is_scorable'], 'filter', 'filter' => 'boolval'],
            [['survey_question_name'], 'string', 'max' => 130],
            [['survey_question_name'], 'required'],
            [['survey_question_survey_id'], 'exist', 'skipOnError' => true, 'targetClass' => Survey::class, 'targetAttribute' => ['survey_question_survey_id' => 'survey_id']],
            [['survey_question_type'], 'exist', 'skipOnError' => true, 'targetClass' => SurveyType::class, 'targetAttribute' => ['survey_question_type' => 'survey_type_id']],
        ];
    }

    public function beforeSave($insert)
    {
        //scorable questions
        if (!$insert && !in_array($this->survey_question_type, [
            SurveyType::TYPE_MULTIPLE,
            SurveyType::TYPE_ONE_OF_LIST,
            SurveyType::TYPE_DROPDOWN
        ])) {
            if ($this->survey_question_is_scorable){
                $this->survey_question_is_scorable = false;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function loadDefaultValues($skipIfSet = true)
    {
        parent::loadDefaultValues($skipIfSet);
        $this->survey_question_type = SurveyType::TYPE_MULTIPLE; //multiple choice
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'survey_question_id' => Yii::t('survey', 'Question ID'),
            'survey_question_name' => Yii::t('survey', 'Survey Question Name'),
            'survey_question_descr' => Yii::t('survey', 'Detailed description'),
            'survey_question_type' => Yii::t('survey', 'Question Type'),
            'survey_question_survey_id' => Yii::t('survey', 'Survey ID'),
            'survey_question_can_skip' => Yii::t('survey', 'Can be skipped'),
            'survey_question_show_descr' => Yii::t('survey', 'Show detailed description'),
            'survey_question_is_scorable' => Yii::t('survey', 'Score this question'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnswers()
    {
        return $this->hasMany(SurveyAnswer::class, ['survey_answer_question_id' => 'survey_question_id'])
            ->orderBy(['survey_answer_sort' => SORT_ASC, 'survey_answer_id' => SORT_ASC]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSurvey()
    {
        return $this->hasOne(Survey::class, ['survey_id' => 'survey_question_survey_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestionType()
    {
        return $this->hasOne(SurveyType::class, ['survey_type_id' => 'survey_question_type']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAnswers()
    {
        return $this->hasMany(SurveyUserAnswer::class, ['survey_user_answer_question_id' => 'survey_question_id'])
            ->andOnCondition(['survey_user_answer_user_id' => \Yii::$app->user->getId()])
            ->indexBy('survey_user_answer_answer_id');
    }

    /**
     * Returns the total number of users voted for this answer
     *
     * @return int
     */
    public function getTotalUserAnswersCount()
    {
        switch ($this->survey_question_type){
            case SurveyType::TYPE_MULTIPLE:
                $result = SurveyUserAnswer::find()->where(['survey_user_answer_question_id' => $this->survey_question_id])
                    ->andWhere(['survey_user_answer_value' => 1])
                    ->count();
                break;
            case SurveyType::TYPE_ONE_OF_LIST:
            case SurveyType::TYPE_DROPDOWN:
                $result = SurveyUserAnswer::find()->where(['survey_user_answer_question_id' => $this->survey_question_id])
                    ->andWhere(['>', 'survey_user_answer_value', 0])
                    ->count();
                break;
            default:
                $result = 0;
                break;
        }

        return $result;
    }
}
